# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 02:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0002_auto_20171119_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='desc',
            field=models.TextField(),
        ),
    ]
