# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 23:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dojoninja_first', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ninja',
            name='Dojo',
        ),
    ]
