# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 23:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dojoninja_first', '0002_remove_ninja_dojo'),
    ]

    operations = [
        migrations.AddField(
            model_name='ninja',
            name='Dojo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Ninjas', to='dojoninja_first.Dojo'),
        ),
    ]
