# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 01:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dojoninja_first', '0005_auto_20171114_1645'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='Books',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
