# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 01:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_authors', '0002_author_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='Books',
            field=models.ManyToManyField(null=True, related_name='Authors', to='book_authors.Book'),
        ),
    ]
